### ISSUE TITLE
مختصات جغرافیایی

### ISSUE THREAD

**Issue by arezaee** [MajidMohammadian/country_zone_city#1]
با سلام و تشکر بابت زحماتی که کشیدید
جدول خوب کاملیه 
ولی دو تا مورد دیگه هم اگر بهش اضافه بشه خیلی بهتر میشه
مختصات جغرافیایی هر شهر
و استان یا ایالت مربوط به هر شهر
سپاس

**Comment by MajidMohammadian** [comment]
سلام
خواهش می کنم
منظورتون اینه که یه پین رو هر شهر یا استان بخوره؟

**Comment by arezaee** [comment]
منظورم 
latitude و longitude 
هست

**Comment by arezaee** [comment]
یک نسخه کامل از شهرهای ایران اینجا پیدا کردم
https://github.com/jafaripur/iran-locality-database
ولی نسخه شما از اون جایی که مربوط به کل جهان هست اگر کامل بشه خیلی عالی میشه

**Comment by MajidMohammadian** [comment]
شما می تونی با این api آدرس lat , lng هر جایی رو که بخوای تو دیتابیس بزنی
http://maps.googleapis.com/maps/api/geocode/json?address=%D9%85%D8%B4%D9%87%D8%AF

**Comment by arezaee** [comment]
این چه api جالبیه
ممنون
خوبیش اینه که json میده 
و با یک کد ساده میشه دیتابیس رو تکمیل کرد
بازم ممنون

**Comment by MajidMohammadian** [comment]
آره اگر داخلش فارسی و اسم هر کشوری رو بزنی برات میاره
من بیشتر شهر ها رو تست کردم مشکلی نداشت
فقط ممکنه تمام اسم هایی که تو دیتابیس هستن درست نباشن
مثلا من زدم احمد آباد
رفت احمد آباد تو هند رو برام آورد
از این بابت باید حواست جمع باشه

**Comment by MajidMohammadian** [comment]
اگر درست شد و اوکی بود
درخواستش رو بدین به من تا تو همین برنچ مرج کنمش

**Comment by arezaee** [comment]
باشه. حتما
